# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a15tcpg236-2I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/CORDIC_LN_1/CORDIC_LN_1.cache/wt [current_project]
set_property parent.project_path D:/CORDIC_LN_1/CORDIC_LN_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib D:/proyecto/Proyecto_De_Graduacion-master/Coprocesador_CORDIC_RTL/d_ff_en.v
synth_design -top FF_D -part xa7a15tcpg236-2I
write_checkpoint -noxdef FF_D.dcp
catch { report_utilization -file FF_D_utilization_synth.rpt -pb FF_D_utilization_synth.pb }
