# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a15tcpg236-2I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Adrián/Desktop/CORDIC_LN_1/CORDIC_LN_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Adrián/Desktop/CORDIC_LN_1/CORDIC_LN_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib C:/Users/Adrián/Desktop/CORDIC_LN_1/CORDIC_LN_1.srcs/sources_1/new/LUT_SHIFT.v
synth_design -top LUT_SHIFT -part xa7a15tcpg236-2I
write_checkpoint -noxdef LUT_SHIFT.dcp
catch { report_utilization -file LUT_SHIFT_utilization_synth.rpt -pb LUT_SHIFT_utilization_synth.pb }
